name: Run GraphQL Query

on:
  push:
    branches:
      - main

jobs:
  run-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @apollo/client graphql cross-fetch

      - name: Run GraphQL Query
        run: node run-query.js
        env:
          GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}
